const arr = [
  {
    id: 1,
    companyName: "Figma",
    image: "figma.png",
    status_image: "green.png",
    userCard: 2468,
    userMail: "Itai Bracha31@gmail.com",
    lastTrx: "02-06-22",
    sumTrx: 783.22,
    status: "done",
    endDate: "12-12-22",
    total: 783.22,
    cardType: "Visa",
    userName: "Itai Bracha",
  },
  {
    id: 2,
    companyName: "Adobe XD",
    image: "xd.jpg",
    status_image: "green.png",
    userCard: 2468,
    userMail: "Itai Bracha32@gmail.com",
    lastTrx: "02-06-22",
    sumTrx: 783.22,
    status: "done",
    endDate: "12-12-22",
    total: 783.22,
    cardType: "Visa",
    userName: "Itai Bracha",
  },
  {
    id: 3,
    companyName: "Mailchimp",
    image: "mailchimp.png",
    status_image: "green.png",
    userCard: 2468,
    userMail: "Itai Bracha312@gmail.com",
    lastTrx: "02-06-22",
    sumTrx: 2468,
    status: "done",
    endDate: "12-12-22",
    total: 783.22,
    cardType: "Visa",
    userName: "Itai Bracha",
  },
  {
    id: 4,
    companyName: "WIX",
    image: "Vector.png",
    status_image: "orange.png",
    userCard: 2468,
    userMail: "Itai Bracha777@gmail.com",
    lastTrx: "02-06-22",
    sumTrx: 783.22,
    status: "pending",
    endDate: "12-12-22",
    total: 555,
    cardType: "Visa",
    userName: "Itai Bracha",
  },
  {
    id: 5,
    companyName: "Youtube",
    image: "youtube.png",
    status_image: "green.png",
    userCard: 2468,
    userMail: "Itai 111@gmail.com",
    lastTrx: "02-06-22",
    sumTrx: 783.22,
    status: "done",
    endDate: "12-12-22",
    total: 777,
    cardType: "Visa",
    userName: "Itai Bracha",
  },
];

export default arr;
